name: Loading Animations for React
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build  
        run: |
          npm install
          npm run build

      - name: Publish lib to NPM 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
        run: npm publish lib/ --access public
    
    - name: Deploy demo 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: demo/dist/ # The folder the action should deploy.








        # continue-on-error: true
      # - uses: actions/setup-node@v2
      #   with:
      #     registry-url: 'https://npm.pkg.github.com'
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   continue-on-error: true
